apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-nodejs
spec:
  selector:
    app: ecsdemo-nodejs
  ports:
   -  protocol: {{.Values.Service.ports.protocol}}
      port: {{.Values.Service.ports.port}}
      targetPort: {{.Values.Service.ports.targetPort}}

